### ISSUE TITLE
Add description to each "most robust xmpp providers"

### ISSUE THREAD

**Issue by koppor** [bluszcz/awesome-xmpp#10]
Cloud you please a short description after each "most robust xmpp provider"? https://github.com/bluszcz/awesome-xmpp#most-robust-xmpp-providers.

Maybe, put the generation howto after the list. I do not know, how hard the awesomelist guys are. Maybe, this howto has to be moved to `CONTRIBUTING.md` somehow. I think, the "Extracted with" is really something for admins of the list and not for the average reader. For instance, for the other entries in the list, there is no reasoning, why they are in. 😇

**Comment by bluszcz** [comment]
Hello, send proposed PR please how would you like to see it. Thanks for the contribution.
