### ISSUE TITLE
A few things to add

### ISSUE THREAD

**Issue by poVoq** [bluszcz/awesome-xmpp#13]
First off, thanks a lot for making me aware of the Saros project :)

For clients please add:
https://git.kaidan.im/kaidan/kaidan/ (Cross-platform)
https://uwpx.org/ (Windows10)
https://yaxim.org/ (Android)
(https://omemo.top/ is a nice source for clients)

For advanced use please add:
https://github.com/louiz/biboumi (really nice IRC gateway)
https://salut-a-toi.org/ (a client but also various other advanced uses)

**Comment by ukata** [comment]
I'm on it.

**Comment by bluszcz** [comment]
Thanks for suggestion @poVoq  and thanks for contribution @ukata
