### ISSUE TITLE
IM Observatory has been discontinued since October 2022

### ISSUE THREAD

**Issue by Darkflib** [bluszcz/awesome-xmpp#33]
IM Observatory

Testing the security of the Jabber/XMPP network.

This service has been discontinued since October 2022.

The IM Observatory was a project started in 2013 by security researcher [Thijs Alkemade](https://twitter.com/xnyhps) to test the security of services on the XMPP network.

For many years the project has been maintained by various community members, but after 10 years of operation, the service has become a growing burden to maintain in terms of both development and hosting. Meanwhile, the internet's security landscape has changed - OpenSSL, distributions and applications are now far more aware of the kinds of issues that the IM Observatory highlighted, and default settings are far more secure than they used to be. With the availability of Let's Encrypt since 2016 and today's widespread availability of free certificates, setting up a server that follows best security practices is now easier than ever.

The source code for the IM Observatory was all open-source, and can still be found under the [xmpp-observatory organization on Github](https://github.com/xmpp-observatory).

A similar project is under development that will provide many of the insights that the IM Observatory used to provide. An early preview of this service is available at [inspect.xmpp.net](https://inspect.xmpp.net/) and the code can be found at [xmpp-observatory/testxmpp on Github](https://github.com/xmpp-observatory/testxmpp). For quick testing that an XMPP service is functioning correctly with valid certificates, see also [connect.xmpp.net](https://connect.xmpp.net/).

**Comment by bluszcz** [comment]
Please feel free to do the PR to fix it :)

**Comment by Darkflib** [comment]
At the time, I hadn't the spare capacity to do so... But I often would have done soOn 4 Jul 2024 17:50, Rafał Zawadzki ***@***.***> wrote:
Please feel free to do the PR to fix it :)
